### ISSUE TITLE
Implement linespacing attribute

### ISSUE THREAD

**Issue by steeffeen-zz** [steeffeen-zz/FancyManiaLinks#18]
Label & TextEdit receives new linespacing attribute

**Comment by steeffeen-zz** [comment]
"TextEdit" probably means "Entry"

**Comment by PRGfx** [comment]
No, TextEdit is it's own element: https://forum.maniaplanet.com/viewtopic.php?f=464&t=29493
Entry has no multi line anymore and thus no line spacing

**Comment by steeffeen-zz** [comment]
Thank you very much for pointing this out! I remember reading this post but I completely forgot about it...

**Comment by steeffeen-zz** [comment]
Requires #22

**Comment by steeffeen-zz** [comment]
Done
