### ISSUE TITLE
Implement scriptaction attribute

### ISSUE THREAD

**Issue by steeffeen-zz** [steeffeen-zz/FancyManiaLinks#21]
Controls receive a new scriptaction attribute

**Comment by PRGfx** [comment]
Maybe something like
```php
setScriptAction($action, array() $arguments=array())
```
would be a more comprehensive syntax. I'm not sure how it handles escaping ' in arguments, but this string composition in general would be a nice thing to be handled by the framework imo.

(Regarding getScriptAction it would probably be better to use some data object instead.)

**Comment by steeffeen-zz** [comment]
@PRGfx This is a good suggestion! Thanks!
I'm thinking about additional get/setScriptActionParameters methods instead of a data object in order to have a comprehensible API.
