### ISSUE TITLE
Change Linespacing default -1

### ISSUE THREAD

**Issue by kremsy** [steeffeen-zz/FancyManiaLinks#27]
(-1 changes the order of the lines)

**Comment by steeffeen-zz** [comment]
I intended that the default value -1 wouldn't be rendered at all. However, it seems that a negative line spacing is actually valid and simply reorders the lines from bottom to top.
The actual default value should probably be 1 while any other value should be rendered (-1 as well).

**Comment by kremsy** [comment]
Maybe you can make also  Reorder Method if someone ever wants todo that^^

**Comment by PRGfx** [comment]
Depending on the outcome of [this](https://forum.maniaplanet.com/viewtopic.php?f=559&t=39968) you could enforce things like autonewline if linespacing is set to !=1.

Well and reversing the line order could be useful e.g. for printing a log ordered by the most recent entries first. The control conveniently changes the render origin accordingly and doesn't just stupidly stack the next lines higher and higher.

**Comment by steeffeen-zz** [comment]
Reversing the line order will be possible by setting the value to -1 but I don't think I will add an additional convenience method for that. 

I will keep an eye on the thread, thanks.
