### ISSUE TITLE
ToolTipFeature does not work

### ISSUE THREAD

**Issue by kremsy** [steeffeen-zz/FancyManiaLinks#28]
All Controllers are stacked over eachother (ToolTipLabelFeature) works

**Comment by steeffeen-zz** [comment]
I can't find a difference in the FML code and the tooltip examples are working fine.
How can I reproduce the issue?

**Comment by steeffeen** [comment]
the issue seems to be the incompatible change regarding addTooltipFeature/addTooltipLabelFeature

**Comment by steeffeen-zz** [comment]
Closing this issue for now as I can't reproduce it. Please reopen if necessary and attach a screenshot of the ingame console.
