### ISSUE TITLE
Paging Compatibility Error

### ISSUE THREAD

**Issue by kremsy** [steeffeen-zz/FancyManiaLinks#31]
25-Mar-2017 18:15:50 UTC] [PHP RECOVERABLE ERROR]: Argument 1 passed to FML\Script\Features\Paging::addPage() must be an instance of FML\Script\Features\PagingPage, instance of FML\Controls\Frame given, called in /home/smparagon19/ManiaControlSynced/core/Commands/HelpManager.php on line 185 and defined

**Comment by steeffeen-zz** [comment]
Please use Paging::addPageControl() instead. This is an incompatibility that I don't want to roll back, even though I regret implementing it.
Sorry for the inconveniences!

**Comment by kremsy** [comment]
guess its fine, MC plugins will update anyways
