### ISSUE TITLE
add favourite does not work anymore

### ISSUE THREAD

**Issue by kremsy** [steeffeen-zz/FancyManiaLinks#33]
The Add Favourite we use in ManiaControl on Top left doesnt work anymore

**Comment by steeffeen-zz** [comment]
This was probably the case because the maniacontrol manialink wasn't registered in MP4. I've done this just now.  (https://github.com/ManiaControl/ManiaControl/blob/master/plugins/MCTeam/WidgetPlugin.php#L371)
Please retest. The code seems to be working fine when executed directly.

**Comment by kremsy** [comment]
works now 👍
