### ISSUE TITLE
MP4 setScoretableVisibility does not work anymore

### ISSUE THREAD

**Issue by kremsy** [steeffeen-zz/FancyManiaLinks#35]
The FML/CustomUI/setScoretableVisible doesn't work anymore

**Comment by steeffeen-zz** [comment]
This might be the case because Nadeo changes the Custom UI API in MP4.
Needs further investigation.

**Comment by kremsy** [comment]
Seems like it is a nadeo Bug, eole told me he will look into it, don't think its an FML bug.

**Comment by steeffeen-zz** [comment]
Closing for now, please reopen if necessary.
