### ISSUE TITLE
setWidth + setAction on Label does not work

### ISSUE THREAD

**Issue by kremsy** [steeffeen-zz/FancyManiaLinks#36]
Setting a Width and a action a label makes the label dissapear. (If you set either of the values all works fine).

Example: 
https://github.com/ManiaControl/ManiaControl/commit/0b9ee124cc87e6a8d8fe94ded18302f0597e7d33

**Comment by kremsy** [comment]
After debugging we saw that the output of this label is:

<label pos="-16 0" posn="-16 0 0" size="44 -1" sizen="44 -1" width="44" halign="left" valign="center2" text="NONO91" textprefix="$s" action="ManiaExchangeList.GetMapsFromAuthor.NONO91" linespacing="-1" style="TextCardSmall" textsize="1" textcolor="FFF"/>

And the problem is the -1 at the size, setting it to a possitive value (like 5) solved the issue, so using -1 as defaults made the problem. (someone told me also that you should never set linespacing to -1 too)

**Comment by steeffeen-zz** [comment]
Rendering a size of "PositiveWidth NegativeHeight" or the other way around leads to this problem. It occures because of the default values -1.
It seems like changing the default values to 0 would fix it.
