### ISSUE TITLE
Wish: Manialink Render Echo without ManiaScript

### ISSUE THREAD

**Issue by kremsy** [steeffeen-zz/FancyManiaLinks#37]
Possibility to dump / render the manialink with the echo parameter without appending the script. Most of the times in real cases the script is so long that its almost impossible to debug probably with it, if you disable the script render on the echo it shows usefull debug results.

**Comment by steeffeen-zz** [comment]
For now I'm adding a __toString() method to the Control class. A ManiaLink isn't complete without its script (because of the dynamic script features etc.), so I claim that you're mainly interesting in debugging control XML.
