### ISSUE TITLE
Implement MP4 UI Properties

### ISSUE THREAD

**Issue by steeffeen-zz** [steeffeen-zz/FancyManiaLinks#42]
See
ShootMania: https://github.com/maniaplanet/script-xmlrpc/blob/master/XmlRpcListing.md#shootmaniauisetproperties
TrackMania: https://github.com/maniaplanet/script-xmlrpc/blob/master/XmlRpcListing.md#trackmaniauisetproperties

**Comment by Vincent-P** [comment]
Hello,
I'm really sorry for writing something with no relations with this repository.
Obstacle is currently broken with Maniaplanet 4, and it doesn't seem like you're updating it.
Is someone currently working on it?
If not, I would happily update and maintain it if you could give me the source of the Title Pack.

**Comment by steeffeen-zz** [comment]
Replaces CustomUI

**Comment by steeffeen-zz** [comment]
Done
