### ISSUE TITLE
Script Feature to toggle ManiaLink via Key Press

### ISSUE THREAD

**Issue by steeffeen-zz** [steeffeen-zz/FancyManiaLinks#45]
Pressing a Key like F9 should simply toggle the visibility of the complete manialink

**Comment by kremsy** [comment]
Important that it applies to all manialinks, if you press F9 to hide and a new manialink get sent it should be hidden as well.

**Comment by kremsy** [comment]
(all manialinks sent with the fml)

**Comment by steeffeen-zz** [comment]
Good hint!
But if it would be included in all manialinks that would mean that manialinks not related to server controllers would also have it. This would make it possible to hide a manialink in the browser which wouldn't make much sense of course.
This is why you will have to add the feature to each manialink.

**Comment by steeffeen-zz** [comment]
See Example: https://github.com/steeffeen/FancyManiaLinks/blob/master/examples/toggleInterface.php

**Comment by kremsy** [comment]
![grafik](https://user-images.githubusercontent.com/2006941/27398422-fbb04114-56b9-11e7-8352-d38b84269683.png)

**Comment by steeffeen-zz** [comment]
reopen as it doesn't work yet

**Comment by steeffeen-zz** [comment]
Opened forum post regarding the MainFrame object: https://forum.maniaplanet.com/viewtopic.php?f=279&t=42074
Currently the only solution to get this working would be to add a dedicated container frame element that would get toggled

**Comment by steeffeen-zz** [comment]
As there doesn't seem to be a possibility to support this out-of-box I will change the ToggleInterface feature so that the consumer has to provide the control (main frame) that is being toggled.

(Injecting an implicit main frame is feasible but messes up the hierarchy of the manialink content. Therefore, that's not an option.)
